const ADD_ALBUM=1;
const UPDATE_ALBUM=2;
const HANDLE_INPUT_CHANGES=3;
const HANDLE_EDIT=4;
const HANDLE_DELETE=5;
const HANDLE_SEARCH=6;
const RESET_FORM=7

export {
    ADD_ALBUM,
    UPDATE_ALBUM,
    HANDLE_INPUT_CHANGES,
    HANDLE_EDIT,
    HANDLE_DELETE,
    HANDLE_SEARCH,
    RESET_FORM,
};
