const CREATE_GOREST = 1;
const UPDATE_GOREST = 2;
const DELETE_GOREST = 3;
const EDIT_GOREST = 4;
const RESET_GOREST = 5;
const FETCH_GOREST = 6;
const FETCH_COMPLETE_GOREST = 7;

export{
    CREATE_GOREST, UPDATE_GOREST, DELETE_GOREST, EDIT_GOREST, RESET_GOREST,
    FETCH_GOREST, FETCH_COMPLETE_GOREST
}
